Description: Cloud Formation script to define IAM Role needed to allow EC2 instances use the S3 Service by Omole John www.johnomole.me

Parameters:
  EnvironmentName: 
    Description: Env Name that will be prefixed in order to access Variables exported from our networking Resources
    Type: String

Resources:
  IAMRoleWebApp:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"

  IAMWebAppS3IP:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - Ref: "IAMRoleWebApp"

Outputs:
  IAMRoleWebApp:
    Description: "Allow EC2 instances to manage Web App S3"
    Value: !Ref IAMWebAppS3IP
    Export:
      Name: !Sub ${EnvironmentName}-IAM-NAME
  IAMRoleWebAppArn:
    Description: Iam Instance Profile Arn
    Value: !GetAtt IAMRoleWebApp.Arn
    Export:
      Name: !Sub ${EnvironmentName}-IAM-ARN